# Generated by Django 4.0.3 on 2022-03-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='last_name',
            new_name='roll',
        ),
    ]
